backend:
  image: backend
  container_name: backend
  ports:
    - 5000:5000

frontend:
  image: frontend
  container_name: frontend
  ports:
    - 4000:4000

nginx:
  image: nginx
  container_name: nginx
  ports:
    - 80:80
    - 443:443
  links:
    - backend
    - frontend
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf