swagger: "2.0"
info:
  description: "Backend API specification for PROGRI BI system"
  version: "0.1"
  title: "Progri BI"
  contact:
    email: "earlyr@yandex.ru"
host: "localhost"
basePath: "/api"

tags:
  - name: "tables"
    description: "API related to operations with tables"

paths:
  /echo:
    get:
      summary: "Check if server is alive"
      responses:
        "200": 
          description: "Alive"
  /tables:
    post:
      summary: "Creates a new table"
      responses:
        "201":
          description: "New table created"
          schema: 
            type: object
            properties:
              id:
                type: integer
                description: The table ID.
        "400":
          description: "Bad file for table"
        "500":
          description: "Server error"
      operationId: "addTable"
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: fileupload
          type: file
          description: "A file to upload"